// <auto-generated />
using EfIntroSolution.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfIntroSolution.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191002125204_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("EfIntroSolution.Models.Laptop", b =>
                {
                    b.Property<int>("LaptopId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Hd");

                    b.Property<float>("Price");

                    b.Property<int>("ProductId");

                    b.Property<float>("Screen");

                    b.Property<float>("Speed");

                    b.HasKey("LaptopId");

                    b.HasIndex("ProductId");

                    b.ToTable("laptops");
                });

            modelBuilder.Entity("EfIntroSolution.Models.Pc", b =>
                {
                    b.Property<int>("PcId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Hd");

                    b.Property<float>("Price");

                    b.Property<int>("ProductId");

                    b.Property<float>("Speed");

                    b.HasKey("PcId");

                    b.HasIndex("ProductId");

                    b.ToTable("pcs");
                });

            modelBuilder.Entity("EfIntroSolution.Models.Printer", b =>
                {
                    b.Property<int>("PrinterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<float>("Price");

                    b.Property<int>("ProductId");

                    b.Property<string>("type");

                    b.HasKey("PrinterId");

                    b.HasIndex("ProductId");

                    b.ToTable("printers");
                });

            modelBuilder.Entity("EfIntroSolution.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Maker");

                    b.Property<string>("Model");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("EfIntroSolution.Models.Laptop", b =>
                {
                    b.HasOne("EfIntroSolution.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EfIntroSolution.Models.Pc", b =>
                {
                    b.HasOne("EfIntroSolution.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EfIntroSolution.Models.Printer", b =>
                {
                    b.HasOne("EfIntroSolution.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
